### ISSUE TITLE
Deja de funcionar cuando rota la pantalla

### ISSUE THREAD

**Issue by Cabezaa** [JuampiOrlando/TPO2#1]
Bueno, lo que pasa es que a la hora de rotar la pantalla o minimizar la app, deja de funcionar ya que el metodo **onDraw** lanza excepcion de fuera de rango. Seguramente a la hora de dibujar los pixeles, como rota, tiene q recalcular las longitudes de ancho y largo, y las confunde.

**Comment by JuampiOrlando** [comment]
Claro! Todavia no pusimos ni controlamos los cambios de estado! No estamos guardando el estadoo!!

**Comment by Cabezaa** [comment]
Solucionado
